# Game settings
AGENT_COUNT = 100
STOP_QUANTITY = 10

# Event timing
TURN_EVIL_TICKS = 200
REGENERATE_TICKS = 100

# Good Agent settings
GOOD_COLOR = "blue"
GOOD_RADIUS = 20
GOOD_SPEED = 50
GOOD_POWER = 1
GOOD_HEALTH = 100

# Evil Agent settings
EVIL_COLOR = "red"
EVIL_RADIUS_MULTIPLIER = 1.1
EVIL_SPEED_MULTIPLIER = 1.1
EVIL_POWER_MULTIPLIER = 1.1
EVIL_HEALTH_MULTIPLIER = 1.1
TURN_EVIL_PROBABILITY = 0.05

# Aftermath settings
RADIUS_INCREASE_AFTER_WIN = 0.25
POWER_INCREASE_AFTER_WIN = 0.25
